spring:
  application:
    name: pdfRAG
    swagger:
      api:
        title: Theology of Arithmetic Tutor
        description: A Rest API for query openAI gpt-4 with a pgvector store RAG
  datasource:
    url: jdbc:postgresql://localhost:5432/pdfRAG
    username: admin
    password: password
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: LLaVA
      chat:
        options:
          model: LLaVA
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        enabled: false
        options:
          model: gpt-4



  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
    main:
      banner-mode: off
  logging:
    level:
      root: off
springdoc:
  swagger-ui:
    path: /swagger-ui.html
