spring:
  application:
    name: pdfRAG
    swagger:
      api:
        title: Theology of Arithmetic Tutor
        description: A Rest API for query openAI gpt-4 with a pgvector store RAG
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      base-url: http://localhost:11434
      embedding:
        options:
          model: llava
          num-thread: 8
          num-gpu: 1
          num-ctx: 4096
          temperature: 0
          top-k: 3
          keep_alive:
      chat:
        options:
          model: llava
    vectorstore:
      oracle:
        index-type: IVF
        distance-type: COSINE
        dimensions: 4096
        forced-normalization: true
  datasource:
    url: jdbc:oracle:thin:@//localhost:50869/freepdb1
    username: mlops
    password: mlops
    oraclepassword: secret
    hikari:
      connection-properties:
        internal_logon: sysdba
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    url: jdbc:oracle:thin:@//localhost:50869/freepdb1



logging:
  level:
    liquibase: DEBUG


#    openai:
#      api-key: ${OPEN_AI_KEY}
#      chat:
#        enabled: false
#        options:
#          model: gpt-4

  sql:
    init:
      mode: always


  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
    main:
      banner-mode: off
  logging:
    level:
      root: off
springdoc:
  swagger-ui:
    path: /swagger-ui.html