services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'PGUSER= admin'
      - 'POSTGRES_DB=pdfRAG'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
