services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'PGUSER= admin'
      - 'POSTGRES_DB=pdfRAG'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'

  ollama:
    image: 'ollama/ollama:latest'
    volumes: ollamadata:/root/.ollama
    ports: '11434:11434'

volumes:
  ollamadata:
    driver: 'local'
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${local_filesystem}