services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    volumes:
      - ollamadata:/root/.ollama

  oracle:
    image: 'gvenzl/oracle-free:latest'
    environment:
      - 'ORACLE_PASSWORD=secret'
      - 'APP_USER=mlops'
      - 'APP_USER_PASSWORD=mlops'
    ports:
      - '50869:1521'
volumes:
  ollamadata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\\Users\\alest\\Workspace\\OllamModels